#
# Jekyll configuration
#
auto: true
permalink: /blog/:title
pygments: true
lsi: true
#markdown: rdiscount
markdown: maruku
maruku:
  use_tex:    false
  use_divs:   false
#rdiscount
#  extensions: [smart]

#
# Site configuration
#
base_url: n47mcc.github.io
url: n47mcc.github.io
title: "/home/dan"
description: "Nat McCormick's Personal Website" 
author: "Nat McCormick"
email: "mccormickn@gmail.com" 
#gauaid: "UA-1697171-11" 
##disqusshortname: "danielsmillercom"
